### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by LeBaux** [JorisSpruyt/Social-Event-Wall#1]
Hi, is there a demo somewhere? I have also hit the wall with the commercial solutions, and I would love to see yours in action. Pardon my BFU behavior, I know I could set it up myself, but after a long day trying million services I thought I just ask :+1: Thanks!

**Comment by JorisSpruyt** [comment]
Hi

The code is currently still running on http://slorarock.be/socialwall/socialwall.html
Know that this is not like other commercial set-ups, that you can just start using. This will require some coding to adjust the project to your needs. If you have any other questions just let me know
