### ISSUE TITLE
Getting errors in browser console, images don't load. [screenshot attached]

### ISSUE THREAD

**Issue by idebashish** [JorisSpruyt/Social-Event-Wall#2]

**Comment by JorisSpruyt** [comment]
Hi Idebashish, 

Can you make sure to provide all the relevant information? I don't see any screenshot here. 

First off, does your server support php? Can you access the getInstagram.php file directly, if so what do you see there?

**Comment by JorisSpruyt** [comment]
Closing as duplicate
